/*
 * Copyright (c) Cherri
 */

package main

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// The machine-readable action catalog is the shared representation of every
// action definition currently known to the compiler. It is consumed by the
// iOS bridge (CherriActionCatalog), the CLI (--actions-json), and downstream
// tooling such as the Shortcut corpus analyzer, docs generation, and preview
// metadata. Only metadata that is reliably known by Cherri is exposed; absent
// fields are omitted rather than invented.

type catalogParameter struct {
	Name       string   `json:"name"`
	Key        string   `json:"key,omitempty"`
	Type       string   `json:"type"`
	Optional   bool     `json:"optional,omitempty"`
	Infinite   bool     `json:"infinite,omitempty"`
	Reference  bool     `json:"reference,omitempty"`
	Literal    bool     `json:"literal,omitempty"`
	Enum       string   `json:"enum,omitempty"`
	EnumValues []string `json:"enumValues,omitempty"`
	Default    string   `json:"default,omitempty"`
}

type catalogActionInfo struct {
	Name               string             `json:"name"`
	ShortcutIdentifier string             `json:"shortcutIdentifier,omitempty"`
	Title              string             `json:"title,omitempty"`
	Description        string             `json:"description,omitempty"`
	Category           string             `json:"category,omitempty"`
	Subcategory        string             `json:"subcategory,omitempty"`
	Parameters         []catalogParameter `json:"parameters,omitempty"`
	EmittedKeys        []string           `json:"emittedKeys,omitempty"`
	OutputType         string             `json:"outputType,omitempty"`
	MacOnly            bool               `json:"macOnly,omitempty"`
	NonMacOnly         bool               `json:"nonMacOnly,omitempty"`
	MinVersion         float64            `json:"minVersion,omitempty"`
	MaxVersion         float64            `json:"maxVersion,omitempty"`
	Builtin            bool               `json:"builtin,omitempty"`
	Custom             bool               `json:"custom,omitempty"`
	// CompilerConstruct marks entries generated by compiler syntax (control
	// flow, variable assignment) rather than callable action definitions.
	CompilerConstruct bool `json:"compilerConstruct,omitempty"`
	// AppIntent mirrors the descriptor an action emits, derived from
	// actionDefinition.appIntent. The outer identifier is already exposed
	// through shortcutIdentifier and is not duplicated here.
	AppIntent *catalogAppIntent `json:"appIntent,omitempty"`
}

// catalogAppIntent describes what Cherri actually emits for an action's
// AppIntentDescriptor; unspecified optional fields are omitted rather than
// invented.
type catalogAppIntent struct {
	Name                    string `json:"name"`
	BundleIdentifier        string `json:"bundleIdentifier"`
	AppIntentIdentifier     string `json:"appIntentIdentifier"`
	TeamIdentifier          string `json:"teamIdentifier,omitempty"`
	RequiresAppInstallation *bool  `json:"requiresAppInstallation,omitempty"`
}

// catalogAppIntentFor derives the shared catalog facet from the action's
// appIntent definition, reflecting emitted output including the legacy Apple
// TeamIdentifier placeholder for curated Apple actions.
func catalogAppIntentFor(definition *actionDefinition) *catalogAppIntent {
	if definition.appIntent == emptyAppIntent {
		return nil
	}
	var intent = definition.appIntent
	var facet = &catalogAppIntent{
		Name:                    intent.name,
		BundleIdentifier:        intent.bundleIdentifier,
		AppIntentIdentifier:     intent.appIntentIdentifier,
		RequiresAppInstallation: intent.requiresAppInstallation,
	}
	if teamIdentifier, emitted := emittedTeamIdentifier(intent); emitted {
		facet.TeamIdentifier = teamIdentifier
	}
	return facet
}

type actionCatalogResponse struct {
	OK      bool                `json:"ok"`
	Version string              `json:"version,omitempty"`
	Count   int                 `json:"count,omitempty"`
	Actions []catalogActionInfo `json:"actions,omitempty"`
	Error   string              `json:"error,omitempty"`
}

const actionCatalogVersion = "2"

// buildActionCatalog returns a stable, sorted representation of the actions
// map. It must not mutate global compiler state.
func buildActionCatalog() []catalogActionInfo {
	names := make([]string, 0, len(actions))
	for name := range actions {
		names = append(names, name)
	}
	sort.Strings(names)

	catalog := make([]catalogActionInfo, 0, len(names)+len(compilerConstructCatalogEntries()))
	for _, name := range names {
		definition := actions[name]
		if definition == nil {
			continue
		}

		parameters := make([]catalogParameter, 0, len(definition.parameters))
		for _, parameter := range definition.parameters {
			item := catalogParameter{
				Name:      parameter.name,
				Key:       parameter.key,
				Type:      string(parameter.validType),
				Optional:  parameter.optional || parameter.defaultValue != nil,
				Infinite:  parameter.infinite,
				Reference: parameter.ref,
				Literal:   parameter.literal,
				Enum:      parameter.enum,
			}
			if parameter.enum != "" {
				item.EnumValues = append([]string(nil), enumerations[parameter.enum]...)
			}
			if parameter.defaultValue != nil {
				item.Default = fmt.Sprint(parameter.defaultValue)
			}
			parameters = append(parameters, item)
		}

		catalog = append(catalog, catalogActionInfo{
			Name:               name,
			ShortcutIdentifier: catalogShortcutIdentifier(name, definition),
			Title:              definition.doc.title,
			Description:        definition.doc.description,
			Category:           definition.doc.category,
			Subcategory:        definition.doc.subcategory,
			Parameters:         parameters,
			EmittedKeys:        emittedParameterKeys(definition),
			OutputType:         string(definition.outputType),
			MacOnly:            definition.macOnly,
			NonMacOnly:         definition.nonMacOnly,
			MinVersion:         definition.minVersion,
			MaxVersion:         definition.maxVersion,
			Builtin:            definition.builtin,
			Custom:             !definition.builtin,
			AppIntent:          catalogAppIntentFor(definition),
		})
	}

	catalog = append(catalog, compilerConstructCatalogEntries()...)
	return catalog
}

// emittedParameterKeys collects every plist key an action may emit beyond its
// declared parameter keys: static appendParams keys plus dynamically written
// keys declared through emittedKeys.
func emittedParameterKeys(definition *actionDefinition) []string {
	var keys []string
	for key := range definition.appendParams {
		keys = append(keys, key)
	}
	keys = append(keys, definition.emittedKeys...)
	if len(keys) == 0 {
		return nil
	}
	sort.Strings(keys)
	return keys
}

// compilerConstructCatalogEntries publishes identifiers the compiler emits
// through language syntax rather than callable action definitions, so corpus
// analysis and downstream consumers see complete coverage.
var compilerConstructs = []catalogActionInfo{
	{
		Name:               "conditional",
		ShortcutIdentifier: "is.workflow.actions.conditional",
		Title:              "If",
		Category:           "controlflow",
		Builtin:            true,
		CompilerConstruct:  true,
		EmittedKeys:        []string{"GroupingIdentifier", "UUID", "WFCondition", "WFConditions", "WFConditionalActionString", "WFConditionalLegacyComparisonBehavior", "WFControlFlowMode", "WFDate", "WFAnotherDate", "WFInput", "WFAnotherNumber", "WFNumberValue"},
	},
	{
		Name:               "menu",
		ShortcutIdentifier: "is.workflow.actions.choosefrommenu",
		Title:              "Choose from Menu",
		Category:           "controlflow",
		Builtin:            true,
		CompilerConstruct:  true,
		EmittedKeys:        []string{"GroupingIdentifier", "UUID", "WFControlFlowMode", "WFMenuItemAttributedTitle", "WFMenuItemTitle", "WFMenuItems", "WFMenuPrompt"},
	},
	{
		Name:               "repeat",
		ShortcutIdentifier: "is.workflow.actions.repeat.count",
		Title:              "Repeat",
		Category:           "controlflow",
		Builtin:            true,
		CompilerConstruct:  true,
		EmittedKeys:        []string{"GroupingIdentifier", "UUID", "WFControlFlowMode", "WFRepeatCount"},
	},
	{
		Name:               "repeat.each",
		ShortcutIdentifier: "is.workflow.actions.repeat.each",
		Title:              "Repeat with Each",
		Category:           "controlflow",
		Builtin:            true,
		CompilerConstruct:  true,
		EmittedKeys:        []string{"GroupingIdentifier", "UUID", "WFControlFlowMode", "WFInput"},
	},
	{
		Name:               "setVariable",
		ShortcutIdentifier: SetVariableIdentifier,
		Title:              "Set Variable",
		Category:           "controlflow",
		Builtin:            true,
		CompilerConstruct:  true,
		EmittedKeys:        []string{"WFInput", "WFVariableName"},
	},
	{
		Name:               "appendVariable",
		ShortcutIdentifier: AppendVariableIdentifier,
		Title:              "Add to Variable",
		Category:           "controlflow",
		Builtin:            true,
		CompilerConstruct:  true,
		EmittedKeys:        []string{"WFInput", "WFVariableName"},
	},
	{
		Name:               "dictionaryValue",
		ShortcutIdentifier: "is.workflow.actions.dictionary",
		Title:              "Dictionary",
		Category:           "controlflow",
		Builtin:            true,
		CompilerConstruct:  true,
		EmittedKeys:        []string{"WFItems"},
	},
}

func compilerConstructCatalogEntries() []catalogActionInfo {
	return append([]catalogActionInfo(nil), compilerConstructs...)
}

func catalogShortcutIdentifier(name string, definition *actionDefinition) string {
	if definition.overrideIdentifier != "" {
		return definition.overrideIdentifier
	}

	base := "is.workflow.actions"
	if definition.appIdentifier != "" {
		base = definition.appIdentifier
	}
	identifier := definition.identifier
	if identifier == "" {
		identifier = strings.ToLower(name)
	}
	return fmt.Sprintf("%s.%s", base, identifier)
}

// generateActionsJSON prints the full machine-readable action catalog.
func generateActionsJSON() {
	catalog := buildActionCatalog()
	response := actionCatalogResponse{
		OK:      true,
		Version: actionCatalogVersion,
		Count:   len(catalog),
		Actions: catalog,
	}
	encoded, err := json.Marshal(response)
	handle(err)
	fmt.Println(string(encoded))
}
